px4_rovercopter_node:
  ros__parameters:
    obstacle: [True, False]  # obs_acoidance, auto_land
    interface: [True, False] # isJoy, isSimulation
    control_mode: [1, 1, 1] # (X, Y, Z) 0: Disable, 1: Position, 2: Velocity  
    obs_config:
      - 45.0   # Degree (sensor FoV)
      - 1.90   # Threshold Distance
      - 0.39   # Safety Distance
      - 0.19   # Vehicle Radius
      - 0.05   # Avoidance Distance
      - 1.20   # Area Distance
      - 0.32   # Vehicle Height
      - 0.25   # Vehicle_width
      

vl53l5cx_node:
  ros__parameters:
    sensor_resolution: 64
    frequency: 50
    just_bottom: True
    front_pos: [0.0, 0.0, 0.0]
    right_pos: [0.0, 0.0, 0.0]
    left_pos: [0.0, 0.0, 0.0]
